"use client"

import React, { useEffect, useState } from "react"
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog" 
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import moment from "moment"

/* TYPES */
type doctorAgent = {
  id: number
  specialist: string
  description: string
  image?: string
  agentPrompt: string
  voiceId?: string
}

type sessionDetail = {
  id: number
  notes: string
  sessionId: string
  report: {
    doctorType?: string
    agentName?: string
    chiefComplaint?: string
    summary?: string
    symptoms?: string[]
    duration?: string
    severity?: string
    medications?: string[]
    recommendations?: string[]
  } | null
  selectedDoctor: doctorAgent
  createdOn: string
}

/* VIEW REPORT DIALOG */
function ViewReportDialog({ record }: { record: sessionDetail }) {
  const report = record.report ?? {}

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="link" size="sm">
          View Report
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-center text-lg font-semibold">
            Medical AI Consultation Report
          </DialogTitle>
        </DialogHeader>

        {!record.report ? (
          <p className="text-sm text-center text-muted-foreground mt-4">
            Report is still being generated. Please check again later.
          </p>
        ) : (
          <>
            {/* Session Info */}
            <div className="text-sm space-y-1">
              <p><strong>Doctor:</strong> {record.selectedDoctor.specialist}</p>
              <p><strong>Consulted On:</strong> {new Date(record.createdOn).toLocaleString()}</p>
              <p><strong>Notes:</strong> {record.notes}</p>
            </div>

            <Separator className="my-3" />

            {/* Chief Complaint */}
            <div>
              <h3 className="font-semibold text-blue-600">Chief Complaint</h3>
              <p className="text-sm mt-1">{report.chiefComplaint || "—"}</p>
            </div>

            <Separator className="my-3" />

            {/* Summary */}
            <div>
              <h3 className="font-semibold text-blue-600">Summary</h3>
              <p className="text-sm mt-1">{report.summary || "—"}</p>
            </div>

            <Separator className="my-3" />

            {/* Symptoms */}
            <div>
              <h3 className="font-semibold text-blue-600">Symptoms</h3>
              <ul className="list-disc ml-5 text-sm">
                {report.symptoms?.length
                  ? report.symptoms.map((s, i) => <li key={i}>{s}</li>)
                  : <li>—</li>}
              </ul>
            </div>

            <Separator className="my-3" />

            {/* Duration & Severity */}
            <div className="flex justify-between text-sm">
              <p><strong>Duration:</strong> {report.duration || "Not specified"}</p>
              <p><strong>Severity:</strong> {report.severity || "—"}</p>
            </div>

            <Separator className="my-3" />

            {/* Medications */}
            <div>
              <h3 className="font-semibold text-blue-600">Medications</h3>
              <ul className="list-disc ml-5 text-sm">
                {report.medications?.length
                  ? report.medications.map((m, i) => <li key={i}>{m}</li>)
                  : <li>—</li>}
              </ul>
            </div>

            <Separator className="my-3" />

            {/* Recommendations */}
            <div>
              <h3 className="font-semibold text-blue-600">Recommendations</h3>
              <ul className="list-disc ml-5 text-sm">
                {report.recommendations?.length
                  ? report.recommendations.map((r, i) => <li key={i}>{r}</li>)
                  : <li>—</li>}
              </ul>
            </div>

            <Separator className="my-4" />

            <p className="text-xs text-center text-muted-foreground">
              This report is generated by an AI medical assistant for informational purposes only.
            </p>
          </>
        )}
      </DialogContent>
    </Dialog>
  )
}

/* HISTORY TABLE */
function HistoryTable({ historyList }: { historyList?: sessionDetail[] }) {
  const [history, setHistory] = useState<sessionDetail[]>(historyList ?? [])

  /* AUTO-REFRESH: fetch sessions every 5 seconds */
useEffect(() => {
  const fetchHistory = async () => {
    try {
      const res = await fetch("/api/session-chat?sessionId=all") // <--- note the dash
      if (!res.ok) throw new Error("Failed to fetch sessions")
      const data = await res.json()
      setHistory(data)
    } catch (err) {
      console.error("Error fetching session history:", err)
    }
  }

  // Fetch immediately
  fetchHistory()

  // Poll every 5 seconds
  const interval = setInterval(fetchHistory, 5000)
  return () => clearInterval(interval)
}, [])

  return (
    <div>
      <Table>
        <TableCaption>Previous Consultation Reports</TableCaption>

        <TableHeader>
          <TableRow>
            <TableHead>AI Medical Specialist</TableHead>
            <TableHead>Description</TableHead>
            <TableHead>Date</TableHead>
            <TableHead className="text-right">Action</TableHead>
          </TableRow>
        </TableHeader>

        <TableBody>
          {history.length === 0 ? (
            <TableRow>
              <TableCell colSpan={4} className="text-center">
                No consultation history found
              </TableCell>
            </TableRow>
          ) : (
            history.map((record) => (
              <TableRow key={record.id}>
                <TableCell className="font-medium">{record.selectedDoctor.specialist}</TableCell>
                <TableCell>{record.notes}</TableCell>
                <TableCell>{moment(record.createdOn).fromNow()}</TableCell>
                <TableCell className="text-right">
                  {record.report ? (
                    <ViewReportDialog record={record} />
                  ) : (
                    <span className="text-xs text-muted-foreground">
                      Processing…
                    </span>
                  )}
                </TableCell>
              </TableRow>
            ))
          )}
        </TableBody>
      </Table>
    </div>
  )
}

export default HistoryTable