"use client"

import React from "react"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"

/* SAME TYPE AS HistoryTable */
type doctorAgent = {
  specialist: string
}

type sessionDetail = {
  id: number
  notes: string
  sessionId: string
  report: {
    doctorType?: string
    agentName?: string
    chiefComplaint?: string
    summary?: string
    symptoms?: string[]
    duration?: string
    severity?: string
    medications?: string[]
    recommendations?: string[]
  }
  selectedDoctor: doctorAgent
  createdOn: string
}

type Props = {
  record: sessionDetail
}

function ViewReportDialog({ record }: Props) {
//   const report = record.report
const report = record.report ?? {}
if (!record.report) {
    return (
      <Dialog>
        <DialogTrigger asChild>
          <Button variant="link" size="sm">
            View Report
          </Button>
        </DialogTrigger>

        <DialogContent>
          <DialogHeader>
            <DialogTitle>Medical AI Consultation Report</DialogTitle>
          </DialogHeader>

          <p className="text-sm text-center text-muted-foreground mt-4">
            Report is still being generated. Please check again later.
          </p>
        </DialogContent>
      </Dialog>
    )
  }
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="link" size="sm">
          View Report
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-2xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-center text-lg font-semibold">
            Medical AI Consultation Report
          </DialogTitle>
        </DialogHeader>

        {/* Session Info */}
        <div className="text-sm space-y-1">
          <p><strong>Doctor:</strong> {record.selectedDoctor.specialist}</p>
          <p><strong>Consulted On:</strong> {new Date(record.createdOn).toLocaleString()}</p>
          <p><strong>Notes:</strong> {record.notes}</p>
        </div>

        <Separator className="my-3" />

        {/* Chief Complaint */}
        <div>
          <h3 className="font-semibold text-blue-600">Chief Complaint</h3>
          <p className="text-sm mt-1">{report.chiefComplaint || "—"}</p>
        </div>

        <Separator className="my-3" />

        {/* Summary */}
        <div>
          <h3 className="font-semibold text-blue-600">Summary</h3>
          <p className="text-sm mt-1">{report.summary || "—"}</p>
        </div>

        <Separator className="my-3" />

        {/* Symptoms */} 
        <div>
          <h3 className="font-semibold text-blue-600">Symptoms</h3>
          <ul className="list-disc ml-5 text-sm">
            {report.symptoms?.map((s, i) => (
              <li key={i}>{s}</li>
            )) || <li>—</li>}
          </ul>
        </div>

        <Separator className="my-3" />

        {/* Duration & Severity */}
        <div className="flex justify-between text-sm">
          <p><strong>Duration:</strong> {report.duration || "Not specified"}</p>
          <p><strong>Severity:</strong> {report.severity || "—"}</p>
        </div>

        <Separator className="my-3" />

        {/* Medications */}
        <div>
          <h3 className="font-semibold text-blue-600">Medications</h3>
          <ul className="list-disc ml-5 text-sm">
            {report.medications?.map((m, i) => (
              <li key={i}>{m}</li>
            )) || <li>—</li>}
          </ul>
        </div>

        <Separator className="my-3" />

        {/* Recommendations */}
        <div>
          <h3 className="font-semibold text-blue-600">Recommendations</h3>
          <ul className="list-disc ml-5 text-sm">
            {report.recommendations?.map((r, i) => (
              <li key={i}>{r}</li>
            )) || <li>—</li>}
          </ul>
        </div>

        <Separator className="my-4" />

        <p className="text-xs text-center text-muted-foreground">
          This report is generated by an AI medical assistant for informational purposes only.
        </p>
      </DialogContent>
    </Dialog>
  )
}

export default ViewReportDialog